In [29]:
# gerekli libraries

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [30]:
dataset=pd.read_csv("iris.csv")
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [31]:
#split data
X=dataset.iloc[:,0:4]
y=dataset.iloc[:,4]
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0,test_size=0.33)

In [32]:
# feature scale
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.fit_transform(X_test)

In [33]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [34]:
y_pred = dt.predict(X_test)
# Evaluate the model
cm=confusion_matrix(y_test,y_pred)
print cm
#print f1_score(y_test,y_pred)

[[16  0  0]
 [ 0 18  1]
 [ 0  0 15]]


In [35]:
print accuracy_score(y_test,y_pred)

0.98
