In [1]:

# gerekli libraries

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score


In [3]:
dataset=pd.read_csv("iris.csv")
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [25]:
#split data
X=dataset.iloc[:,0:4]
y=dataset.iloc[:,4]
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0,test_size=0.33)


In [26]:
# feature scale
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.fit_transform(X_test)

In [27]:
import math
print math.sqrt(len(y_test))

7.07106781187


In [35]:
classifier=KNeighborsClassifier(n_neighbors=7,metric='euclidean')
classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
           metric_params=None, n_jobs=None, n_neighbors=7, p=2,
           weights='uniform')

In [36]:
# prediciton on test data
y_pred=classifier.predict(X_test)
print y_pred

['virginica' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'setosa' 'versicolor' 'versicolor' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'setosa' 'versicolor' 'versicolor'
 'setosa' 'setosa' 'virginica' 'versicolor' 'setosa' 'setosa' 'virginica'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'setosa' 'virginica'
 'versicolor' 'setosa' 'virginica' 'virginica' 'versicolor' 'setosa'
 'virginica' 'versicolor' 'versicolor' 'virginica' 'setosa' 'virginica'
 'setosa' 'setosa' 'versicolor' 'virginica' 'virginica' 'versicolor'
 'virginica']


In [37]:
# Evaluate the model
cm=confusion_matrix(y_test,y_pred)
print cm
#print f1_score(y_test,y_pred)

[[16  0  0]
 [ 0 18  1]
 [ 0  1 14]]


In [38]:
print accuracy_score(y_test,y_pred)

0.96
